# Generated by Django 4.0 on 2022-03-24 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StudentName', models.CharField(max_length=20)),
                ('ParentName', models.CharField(max_length=20)),
                ('Gender', models.CharField(max_length=20)),
                ('Board', models.CharField(max_length=20)),
                ('StudentClass', models.CharField(max_length=20)),
                ('SchoolName', models.CharField(max_length=20)),
                ('Address', models.CharField(max_length=30)),
                ('StudentEmail', models.CharField(max_length=30)),
                ('StudentPhone', models.CharField(max_length=20)),
                ('ParentPhone', models.CharField(max_length=20)),
                ('StudentPassword', models.CharField(max_length=20)),
            ],
        ),
    ]
