# Generated by Django 4.0 on 2022-03-24 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutionapp', '0002_alter_userregistration_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregistration',
            name='StudentImage',
            field=models.ImageField(blank='true', null='true', upload_to='Student_Images/'),
            preserve_default='true',
        ),
    ]
