# Generated by Django 4.0 on 2022-04-06 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutionapp', '0004_alter_userregistration_board_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contactus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ReqName', models.CharField(max_length=50)),
                ('ReqEmail', models.CharField(max_length=50)),
                ('ReqMobile', models.CharField(max_length=50)),
                ('ReqMessage', models.CharField(max_length=500)),
            ],
        ),
    ]
